### ISSUE TITLE
Merge cross

### ISSUE THREAD

**Issue by Keruspe** [nakamuray/nakamuray-exheres#7]
Can you please merge cross into master and tagging the last non-cross commit?

git tag pre-cross -m "Last commit before cross merge" && git merge cross

Thanks!

**Comment by nakamuray** [comment]
done

**Comment by Keruspe** [comment]
Thanks :)
Don't forget to push the tag ;)

**Comment by nakamuray** [comment]
oops, thanks to notify that.
